name: Feature request
description: Suggest a new feature or enhancement
title: "[FEATURE REQUEST] <title>"
labels: [enhancement]
body:
  - type: checkboxes
    id: low-effort-checks
    attributes:
      label: Please confirm
      description: Feature requests without all checks may be ignored/closed.
      options:
        - label: I have searched existing feature requests
        - label: This feature is not a duplicate of an existing one
        - label: I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
        - label: I have checked for both game and editor updates, and understand that feature requests for older versions may not be considered.

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature or enhancement you are requesting.
      placeholder: |
        I would like to see ...

        Description of the feature:
        1. What problem does it solve?
        2. How would you like to see it implemented?
        3. Any related or similar features in other tools or games?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Benefits
      description: A brief description of the expected benefits or improvements.
      placeholder: This feature will improve ...
    validations:
      required: true

  - type: input
    attributes:
      label: Editor Version
      placeholder: "0.8.1"
    validations:
      required: true

  - type: input
    attributes:
      label: Game Version
      placeholder: "0.3.3"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context...
    validations:
      required: false