version: '3.8'
services:
  palworld-pal-editor:
    image: docker.io/library/palworld-pal-editor
    container_name: palworld-pal-editor
    # network_mode: host
    ports:
      - 12345:12345
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - APP_PORT=12345 # make sure this matches the port you are going to map
      - APP_LANG=zh-CN
      - MODE=web # [cli, web, gui] You are not going to run gui in docker though... ;)
      - SAVE_PATH=/mnt/gamesave
      - PASSWORD=password # remove this env unless you want a password, but password is strongly recommended (for web mode).
    volumes:
      - "/Users/connlost/Coding/Palworld-Pal-Editor/tests/gamesave/AF518B19A47340B8A55BC58137981393:/mnt/gamesave"
