name: Release Build

on:
  push:
    branches:
      - release
    tags:
      - "v*"

jobs:
  dev-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.2
        architecture: x64

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run Windows Builder Script
      if: runner.os == 'Windows'
      shell: pwsh
      run: ./build_executable.ps1

    - name: Run Unix-like Builder Script
      if: runner.os != 'Windows'
      shell: bash
      run: ./build_executable.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Palworld_Pal_Editor_${{ matrix.os }}_artifact
        path: ./dist/

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}